### ISSUE TITLE
Package Pre-Built Binaries in Releases

### ISSUE THREAD

**Issue by tinder-cwybranowski** [Tinder/GitQuery#56]
### Overview
We'd like to consume `gitQuery` as either a prebuilt binary executable artifact to better integrate with our Bazel toolchain. We would also like to avoid Homebrew, and any potential dependencies (gradle) that might be required to install `gitQuery` locally.

Alternatively, if Bazel support can be added to `Tinder/GitQuery`, we could consume that and build `gitQuery` on developer machines as part of the regular toolchain. 

### Pre-Built Binary
If possible, it would be ideal if the `gitQuery` CLI executable could be prebuilt and attached to any given release as an additional artifact. It's totally fine (and expected) that the prebuilt binary still required JDK in the toolchain -- however we'd like to avoid any additional dependencies (gradle) unless absolutely necessary.

### Native Bazel Support
If it's desirable to add native Bazel support to `Tinder/GitQuery`, then our toolchain could easily consume the new Bazel-version of GitQuery, including any dependencies you declare as part of building the CLI.

### Conclusion
Either of the solutions above should work for my use-case, and I'm happy to provide any extra information that would be helpful. Thanks!

**Comment by tinder-aminghadersohi** [comment]
we now have bazel support so this is less needed.
